name: BuildPackage

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    name: Build, test, pack and publish
    runs-on: ubuntu-latest

    steps:
    - name: Check out code onto host
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install node modules
      run: npm ci

    - name: Run unit tests
      run:  npm run test:unit

    - name: Build library
      run:  npm run build-library

    - name: Add NPM CLI
      run: npm install -g npm-cli-login

    - name: Login to NPM
      run: |
        PM_USER=${{ secrets.PCK_USER }} NPM_PASS=${{ secrets.PCK_TOKEN }} NPM_EMAIL=${{ secrets.PCK_EMAIL }} npm-cli-login
        npm publish
