name: BuildPackage

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    name: Build, test, pack and publish
    runs-on: ubuntu-latest

    steps:
    - name: Check out code onto host
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install node modules
      run: npm ci

    - name: Run unit tests
      run:  npm run test:unit

    - name: Build library
      run:  npm run build-library

    - name: configure npm registry proxy
      uses: ahmadnassri/action-github-registry-npm-proxy@v2
      with:
        token: ${{ secrets.PCK_TOKEN }}
        scope: ${{ github.repository_owner }}
        path: ${{ github.workspace }}/.npmrc
        export_user_config: true
